"""Image wait/download helpers for the UI driver."""

from __future__ import annotations

import asyncio
import time
from pathlib import Path

from .errors import BridgeTimeoutError

# Selector for generated images in the conversation. Generated images carry
# alt="Generated image: ..." and a backend-api/estuary/content src (older
# builds used oaiusercontent). Match by alt first, then by src pattern.
IMAGE_SELECTOR = (
    'img[alt^="Generated image"], '
    'img[alt*="Generated by" i], '
    'img[alt*="DALL" i], '
    'img[src*="backend-api/estuary/content"], '
    'img[src*="oaiusercontent"], '
    'img[src*="files.oaiusercontent.com"], '
    'div[data-message-author-role="assistant"] img, '
    'img[src^="data:"]'
)


async def wait_for_image(page, timeout_s: int = 300) -> str:
    """Poll until a generated image appears; return its ``src``.

    Raises :class:`BridgeTimeoutError` if no image appears within ``timeout_s``.
    """
    deadline = time.monotonic() + timeout_s
    while True:
        src = await _find_image_src(page)
        if src:
            return src
        if time.monotonic() >= deadline:
            raise BridgeTimeoutError(
                f"timed out after {timeout_s}s waiting for generated image"
            )
        await asyncio.sleep(1.0)


async def _find_image_src(page) -> str | None:
    """Return the first matching generated image src, ignoring avatar icons."""
    try:
        images = page.locator(IMAGE_SELECTOR)
        count = await images.count()
        for i in range(count):
            img = images.nth(i)
            src = await img.get_attribute("src") or ""
            alt = await img.get_attribute("alt") or ""
            if "avatar" in src.lower() or "profile" in src.lower():
                continue
            if alt.lower() in ("user", "chatgpt", "profile picture"):
                continue
            if src.startswith("http") or src.startswith("data:image"):
                return src
    except Exception:
        pass
    return None


async def save_image(src: str, out_dir: Path, ctx) -> Path:
    """Download an image from ``src`` (url/data/blob) and save it to disk.

    ``ctx`` is a Playwright ``APIRequestContext`` used to fetch remote URLs.
    Returns the path to the saved file.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{int(time.time() * 1000)}.png"
    dest = out_dir / filename

    if src.startswith("data:"):
        content = _decode_data_url(src)
        dest.write_bytes(content)
        return dest

    if src.startswith("blob:"):
        raise BridgeTimeoutError("blob: image URLs require in-page fetch; unsupported")

    # Remote URL: fetch via the request context.
    resp = await ctx.get(src)
    if resp.status != 200:
        raise BridgeTimeoutError(f"failed to download image (status {resp.status})")
    dest.write_bytes(await resp.body())
    return dest


def _decode_data_url(src: str) -> bytes:
    """Decode a ``data:image/png;base64,...`` URL into bytes."""
    import base64

    header, _, b64 = src.partition(",")
    if not b64 or "base64" not in header:
        raise BridgeTimeoutError("unsupported data: URL encoding")
    return base64.b64decode(b64)