"""
Trend Generator Pipeline for XBot Pro.

Runs every 20 minutes (24/7 autonomous generation):
1. Consumes unprocessed ResearchedTopic records generated by the Trend Researcher.
2. Dynamic 4-Way Creation Decision Matrix:
   - 4:5 Vertical Meme / Visual Infographic (VisualEngine)
   - Rich Deep-Dive Thread with Viral Media (generate_thread)
   - Interactive Community Poll (generate_poll / CreatePoll)
   - Punchy Standalone Hot Take (synthesize_creator_post)
3. Stages content as APPROVED directly in the Content table for autonomous publishing.
4. Marks ResearchedTopic as processed and logs in PipelineRun.
"""

from __future__ import annotations

# Re-export internal symbols
from xbot.pipelines.trend_generator_pipeline.collector import (
    _detect_reaction_gif_query,
    _get_default_persona,
    _get_persona_for_profile,
)
from xbot.pipelines.trend_generator_pipeline.pipeline import (
    _run_trend_generator_async,
    generate_content_for_topic,
    run_trend_generator,
    run_trend_generator_for_profile,
)
from xbot.pipelines.trend_generator_pipeline.scorer import determine_creation_format

# Re-export AI engine symbols for backward compatibility & test patching
from xbot.ai.anti_ai_gatekeeper import AntiAIGatekeeper, strip_surrounding_quotes
from xbot.ai.formatting_engine import format_content
from xbot.ai.hook_optimizer import optimize_post_for_virality
from xbot.ai.poll_generator import generate_poll
from xbot.ai.post_synthesizer import synthesize_creator_post
from xbot.ai.thread_generator import generate_thread
from xbot.ai.visual_engine import generate_visual_post_spec

__all__ = [
    "determine_creation_format",
    "generate_content_for_topic",
    "run_trend_generator_for_profile",
    "_run_trend_generator_async",
    "run_trend_generator",
    "_get_persona_for_profile",
    "_get_default_persona",
    "_detect_reaction_gif_query",
    "generate_visual_post_spec",
    "generate_thread",
    "generate_poll",
    "synthesize_creator_post",
    "optimize_post_for_virality",
    "format_content",
    "AntiAIGatekeeper",
    "strip_surrounding_quotes",
]
