"""Initial schema

Revision ID: 41f99bd6b005
Revises: 
Create Date: 2026-06-18 01:34:26.373424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f99bd6b005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_slug', sa.String(length=100), nullable=False),
    sa.Column('x_handle', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'LOCKED', 'SUSPENDED', name='profilestatus'), nullable=False),
    sa.Column('persona_summary', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('proxy_url_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_profiles_profile_slug'), 'profiles', ['profile_slug'], unique=True)
    op.create_index(op.f('ix_profiles_status'), 'profiles', ['status'], unique=False)
    op.create_index(op.f('ix_profiles_x_handle'), 'profiles', ['x_handle'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('total_tweets', sa.Integer(), nullable=False),
    sa.Column('impressions_24h', sa.Integer(), nullable=False),
    sa.Column('engagements_24h', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('top_tweets', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_captured_at'), 'analytics_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_profile_id'), 'analytics_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_snapshot_date'), 'analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('ORIGINAL', 'REPLY', 'QUOTE', 'THREAD', name='contenttype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'FAILED', name='contentstatus'), nullable=False),
    sa.Column('tweet_id', sa.String(length=100), nullable=True),
    sa.Column('performance', sa.JSON(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_created_at'), 'content', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_posted_at'), 'content', ['posted_at'], unique=False)
    op.create_index(op.f('ix_content_profile_id'), 'content', ['profile_id'], unique=False)
    op.create_index(op.f('ix_content_status'), 'content', ['status'], unique=False)
    op.create_index(op.f('ix_content_tweet_id'), 'content', ['tweet_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('count_today', sa.Integer(), nullable=False),
    sa.Column('count_this_hour', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_profile_id'), 'rate_limits', ['profile_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', name='sessionstatus'), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('actions_planned', sa.Integer(), nullable=False),
    sa.Column('actions_completed', sa.Integer(), nullable=False),
    sa.Column('actions_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_profile_id'), 'sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('POST', 'REPLY', 'LIKE', 'RETWEET', 'QUOTE', 'FOLLOW', 'BROWSE', 'SEARCH', name='actiontype'), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTING', 'COMPLETED', 'FAILED', 'SKIPPED', name='actionstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_profile_id'), 'actions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_actions_session_id'), 'actions', ['session_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('action_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('tweet_id', sa.String(length=100), nullable=True),
    sa.Column('initial_likes', sa.Integer(), nullable=False),
    sa.Column('initial_retweets', sa.Integer(), nullable=False),
    sa.Column('initial_replies', sa.Integer(), nullable=False),
    sa.Column('initial_views', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_results_action_id'), 'action_results', ['action_id'], unique=True)
    op.create_index(op.f('ix_action_results_tweet_id'), 'action_results', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_results_tweet_id'), table_name='action_results')
    op.drop_index(op.f('ix_action_results_action_id'), table_name='action_results')
    op.drop_table('action_results')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_session_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_profile_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_profile_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_rate_limits_profile_id'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_content_tweet_id'), table_name='content')
    op.drop_index(op.f('ix_content_status'), table_name='content')
    op.drop_index(op.f('ix_content_profile_id'), table_name='content')
    op.drop_index(op.f('ix_content_posted_at'), table_name='content')
    op.drop_index(op.f('ix_content_created_at'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_date'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_profile_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_captured_at'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_profiles_x_handle'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_status'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_profile_slug'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
