"""add reputation logs

Revision ID: 5039655f9525
Revises: 4e228ec61003
Create Date: 2026-07-08 01:42:56.405570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5039655f9525'
down_revision: Union[str, Sequence[str], None] = '4e228ec61003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('total_replies_analyzed', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_logs_captured_at'), 'reputation_logs', ['captured_at'], unique=False)
    op.create_index(op.f('ix_reputation_logs_profile_id'), 'reputation_logs', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_logs_profile_id'), table_name='reputation_logs')
    op.drop_index(op.f('ix_reputation_logs_captured_at'), table_name='reputation_logs')
    op.drop_table('reputation_logs')
    # ### end Alembic commands ###

